<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;
use Symfony\Component\HttpFoundation\Request;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
}
